apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet2
  template:
    metadata:
      labels:
        app: pet2
    spec:
      imagePullSecrets:
      - name: azure-registry-key
      containers:
      - name: pet2
        image: gorerveli.azurecr.io/dockerpets:v$DOCKER_BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pet2
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30002
  selector:
    app: pet2