apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet
  template:
    metadata:
      labels:
        app: pet
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 700
      imagePullSecrets:
      - name: secret-key
      containers:
      - name: pet
        image: myregistry.domain.com:5000/dockerpets:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "200Mi"
            cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pet
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30000
  selector:
    app: pet
