apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet
  template:
    metadata:
      labels:
        app: pet
    spec:
      imagePullSecrets:
      - name: secret-key
      containers:
      - name: pet
        image: myregistry.domain.com:5000/dockerpets:v$DOCKER_BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pet
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30000
  selector:
    app: pet
